[package]
name = "colorfully"
version = "0.1.0"
edition = "2021"
authors = ["5-23 <yhanbyeol6@gmail.com>"]
description = "your terminal colorfully!"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
